/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testPackages;

import activite.*;
import exception.MissingTradeMarkException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import people.*;
import vehicules.*;

/**
 *
 * @author ante
 */
public class testReferenceSerialization extends javax.swing.JFrame {

    /**
     * Creates new form testReferenceSerialization
     */
    public testReferenceSerialization() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Client = new javax.swing.JLabel();
        TravailClient = new javax.swing.JLabel();
        clientRef = new javax.swing.JLabel();
        travClientRef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Client.setText("Client");

        TravailClient.setText("Travail Client");

        clientRef.setText("jLabel3");

        travClientRef.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clientRef)
                    .addComponent(Client))
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(travClientRef, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TravailClient, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Client)
                    .addComponent(TravailClient))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientRef)
                    .addComponent(travClientRef))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
    Client testCli = new Client();
    Vector<Client> vClient = new Vector<Client>();
    LinkedList<Travail> llTravailPrevu = new LinkedList<Travail>();
    ArrayList<Travail> llTravailEnCours = new ArrayList<Travail>();
    LinkedList<Travail> llTravailFini = new LinkedList<Travail>();
    LinkedList<Vehicule> llVehicules = new LinkedList<Vehicule>();
    
    dataEncapsulate dE = new dataEncapsulate();
    
    try {
    vClient.add(new Client("1", "Marc", "Assin","Rue du veto", "0494100811"));
    vClient.add(new Client("2", "jean", "cive","Rue du veto2", "1494100811"));
    dE.vClient.add(new Client("1", "Marc", "Assin","Rue du veto", "0494100811"));
    dE.vClient.add(new Client("2", "jean", "cive","Rue du veto2", "1494100811"));
    
    llVehicules.add(new Voiture(new TypeVoiture("Renault","test", 4), "11AAA", "2", vClient.get(0)));
    llVehicules.add(new Voiture(new TypeVoiture("Twingo","test2", 3), "222BBB", "3", vClient.get(1)));
    
    
         FileOutputStream fileOut = new FileOutputStream("/tmp/employee.ser");
         ObjectOutputStream out = new ObjectOutputStream(fileOut);
         out.writeObject(testCli);
         out.close();
         fileOut.close();
         System.out.printf("Serialized data is saved in /tmp/employee.ser");
      }catch(IOException i) {
          System.out.println("Error test serialization");
      } catch (MissingTradeMarkException ex) {
            Logger.getLogger(testReferenceSerialization.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testReferenceSerialization().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Client;
    private javax.swing.JLabel TravailClient;
    private javax.swing.JLabel clientRef;
    private javax.swing.JLabel travClientRef;
    // End of variables declaration//GEN-END:variables
}
