/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackages;

/**
 *
 * @author ante
 */
public class aProposForm extends javax.swing.JFrame {

    /**
     * Creates new form aProposForm
     */
    public aProposForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aProposAppLabel = new javax.swing.JLabel();
        aProposReasliselabel = new javax.swing.JLabel();
        aProposJAimeRadBut = new javax.swing.JRadioButton();
        aProposBofRadBut = new javax.swing.JRadioButton();
        aProposDetesteRadBut = new javax.swing.JRadioButton();
        aProposOkButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Garage HEPL - A propos");

        aProposAppLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aProposAppLabel.setText("Application \"Garage HEPL\"");

        aProposReasliselabel.setText("Réalisé par Antoine Brajkovic et Remy Mauhin");

        aProposJAimeRadBut.setSelected(true);
        aProposJAimeRadBut.setText("J'aime");
        aProposJAimeRadBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aProposJAimeRadButMouseClicked(evt);
            }
        });

        aProposBofRadBut.setText("Bof");
        aProposBofRadBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aProposBofRadButMouseClicked(evt);
            }
        });

        aProposDetesteRadBut.setText("Je déteste");
        aProposDetesteRadBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aProposDetesteRadButMouseClicked(evt);
            }
        });
        aProposDetesteRadBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aProposDetesteRadButActionPerformed(evt);
            }
        });

        aProposOkButton.setText("Ok");
        aProposOkButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aProposOkButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aProposReasliselabel)
                            .addComponent(aProposAppLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(aProposJAimeRadBut)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aProposOkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(aProposBofRadBut)
                                .addGap(67, 67, 67)
                                .addComponent(aProposDetesteRadBut)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(aProposAppLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(aProposReasliselabel)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aProposJAimeRadBut)
                    .addComponent(aProposBofRadBut)
                    .addComponent(aProposDetesteRadBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(aProposOkButton)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aProposDetesteRadButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aProposDetesteRadButActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aProposDetesteRadButActionPerformed

    private void aProposOkButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aProposOkButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_aProposOkButtonMouseClicked

    private void aProposJAimeRadButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aProposJAimeRadButMouseClicked
        // TODO add your handling code here:
        aProposJAimeRadBut.setSelected(true);
        aProposBofRadBut.setSelected(false);
        aProposDetesteRadBut.setSelected(false);
    }//GEN-LAST:event_aProposJAimeRadButMouseClicked

    private void aProposBofRadButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aProposBofRadButMouseClicked
        // TODO add your handling code here:
        aProposBofRadBut.setSelected(true);
        aProposDetesteRadBut.setSelected(false);
        aProposJAimeRadBut.setSelected(false);
    }//GEN-LAST:event_aProposBofRadButMouseClicked

    private void aProposDetesteRadButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aProposDetesteRadButMouseClicked
        // TODO add your handling code here:
        aProposDetesteRadBut.setSelected(true);
        aProposBofRadBut.setSelected(false);
        aProposJAimeRadBut.setSelected(false);
    }//GEN-LAST:event_aProposDetesteRadButMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aProposForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aProposForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aProposForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aProposForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aProposForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aProposAppLabel;
    private javax.swing.JRadioButton aProposBofRadBut;
    private javax.swing.JRadioButton aProposDetesteRadBut;
    private javax.swing.JRadioButton aProposJAimeRadBut;
    private javax.swing.JButton aProposOkButton;
    private javax.swing.JLabel aProposReasliselabel;
    // End of variables declaration//GEN-END:variables
}
