/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackages;

import centraleObj.CentraleCommand;
import java.util.Calendar;
import java.util.Random;

/**
 *
 * @author ante
 */
public class commandeForm extends javax.swing.JDialog {
    public static final int PNEU = 0;
    public static final int PIECE = 1;
    public static final int LUBRIFIANT = 2;
    
    
    public int typeApp;
    public int priorite;
    /**
     * Creates new form commandeForm
     */
    public commandeForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public commandeForm(java.awt.Frame parent, boolean modal, int type) {
        super(parent, modal);
        initComponents();
        typeApp = type;
        switch(typeApp)
        {
            case PNEU:
                this.setTitle(this.getTitle()+" PNEU");
                break;
            case PIECE:
                this.setTitle(this.getTitle()+" PIECE");
                break;
            case LUBRIFIANT:
                this.setTitle(this.getTitle()+" LUBRIFIANT");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prioGroupButton = new javax.swing.ButtonGroup();
        commandeLabel = new javax.swing.JLabel();
        urgentRB = new javax.swing.JRadioButton();
        normalRB = new javax.swing.JRadioButton();
        nonPrioRB = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        commandeList = new javax.swing.JList<>();
        commandeListLabel = new javax.swing.JLabel();
        envoyerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        libelleLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        quantiteLabel = new javax.swing.JLabel();
        libelleTF = new javax.swing.JTextField();
        typeTF = new javax.swing.JTextField();
        quantiteTF = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        commandeLabel.setText("Commande :");

        prioGroupButton.add(urgentRB);
        urgentRB.setText("urgent");
        urgentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgentRBActionPerformed(evt);
            }
        });

        prioGroupButton.add(normalRB);
        normalRB.setSelected(true);
        normalRB.setText("normal");
        normalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalRBActionPerformed(evt);
            }
        });

        prioGroupButton.add(nonPrioRB);
        nonPrioRB.setText("non prioritaire");
        nonPrioRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonPrioRBActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(commandeList);

        commandeListLabel.setText("Commandes :");

        envoyerButton.setText("Envoyer");
        envoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        libelleLabel.setText("Libellé :");

        typeLabel.setText("Type :");

        quantiteLabel.setText("Quantité :");

        dateLabel.setText("<Date>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(urgentRB)
                        .addGap(55, 55, 55)
                        .addComponent(normalRB)
                        .addGap(66, 66, 66)
                        .addComponent(nonPrioRB)
                        .addGap(65, 65, 65)
                        .addComponent(commandeListLabel)
                        .addGap(0, 113, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(typeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(libelleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(quantiteTF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(typeTF)
                            .addComponent(libelleTF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(commandeLabel)
                        .addGap(392, 392, 392)
                        .addComponent(dateLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(envoyerButton)
                        .addGap(153, 153, 153)
                        .addComponent(annulerButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(commandeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(dateLabel)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urgentRB)
                    .addComponent(normalRB)
                    .addComponent(nonPrioRB)
                    .addComponent(commandeListLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libelleLabel)
                            .addComponent(libelleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(typeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantiteLabel)
                            .addComponent(quantiteTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envoyerButton)
                    .addComponent(annulerButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_annulerButtonActionPerformed

    private void envoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerButtonActionPerformed
        // TODO add your handling code here:
        try
        {
           String tmpReceive= "";
            CentraleCommand commande = new CentraleCommand("C"+new Random().nextInt(100000000), libelleTF.getText(),typeTF.getText() ,Integer.parseInt(quantiteTF.getText()), priorite, Calendar.getInstance());
            switch(typeApp)
            {
                case PNEU:
                    tmpReceive =applicationGestionForm.serverPneu.sendString(commande.toStringForSend());

                    break;
                case PIECE:
                    tmpReceive = applicationGestionForm.serverPiece.sendString(commande.toStringForSend());
                    break;
                case LUBRIFIANT:
                    tmpReceive = applicationGestionForm.serverLubrifiant.sendString(commande.toStringForSend());
                    break;
            }
            CentraleCommand tmpCommand = new CentraleCommand(tmpReceive);
            mainGarage.dE.vCommand.add(tmpCommand); 
        }
        catch(Exception e)
        {
            System.out.println("S:\t "+e.getMessage());
        }
        this.dispose();
    }//GEN-LAST:event_envoyerButtonActionPerformed

    private void nonPrioRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonPrioRBActionPerformed
        // TODO add your handling code here:
        priorite = CentraleCommand.NONPRIORITAIRE;
    }//GEN-LAST:event_nonPrioRBActionPerformed

    private void urgentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgentRBActionPerformed
        // TODO add your handling code here:
        priorite = CentraleCommand.URGENT;
    }//GEN-LAST:event_urgentRBActionPerformed

    private void normalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalRBActionPerformed
        // TODO add your handling code here:
        priorite = CentraleCommand.PRIORITAIRE;
    }//GEN-LAST:event_normalRBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(commandeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(commandeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(commandeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(commandeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                commandeForm dialog = new commandeForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JLabel commandeLabel;
    private javax.swing.JList<String> commandeList;
    private javax.swing.JLabel commandeListLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton envoyerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel libelleLabel;
    private javax.swing.JTextField libelleTF;
    private javax.swing.JRadioButton nonPrioRB;
    private javax.swing.JRadioButton normalRB;
    private javax.swing.ButtonGroup prioGroupButton;
    private javax.swing.JLabel quantiteLabel;
    private javax.swing.JTextField quantiteTF;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTF;
    private javax.swing.JRadioButton urgentRB;
    // End of variables declaration//GEN-END:variables
}
