/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackages;

/**
 *
 * @author ante
 */
public class commandForm extends javax.swing.JFrame {

    /**
     * Creates new form commandForm
     */
    public commandForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandeLabel = new javax.swing.JLabel();
        urgentRB = new javax.swing.JRadioButton();
        normalRB = new javax.swing.JRadioButton();
        nonPrioRB = new javax.swing.JRadioButton();
        commandeListLabel = new javax.swing.JLabel();
        libelleLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        quantiteLabel = new javax.swing.JLabel();
        envoyerButton = new javax.swing.JButton();
        annulerButton = new javax.swing.JButton();
        commandPanel = new javax.swing.JScrollPane();
        commandList = new javax.swing.JList<>();
        libelleTB = new javax.swing.JTextField();
        typeTB = new javax.swing.JTextField();
        quantiteTB = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Garage HEPL :");

        commandeLabel.setText("Commande :");

        urgentRB.setText("urgent");
        urgentRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urgentRBActionPerformed(evt);
            }
        });

        normalRB.setSelected(true);
        normalRB.setText("normal");
        normalRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalRBActionPerformed(evt);
            }
        });

        nonPrioRB.setText("non prioritaire");
        nonPrioRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonPrioRBActionPerformed(evt);
            }
        });

        commandeListLabel.setText("Commandes :");

        libelleLabel.setText("Libellé :");

        typeLabel.setText("Type");

        quantiteLabel.setText("Quantité :");

        envoyerButton.setText("Envoyer");
        envoyerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envoyerButtonActionPerformed(evt);
            }
        });

        annulerButton.setText("Annuler");
        annulerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerButtonActionPerformed(evt);
            }
        });

        commandPanel.setViewportView(commandList);

        dateLabel.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(urgentRB)
                        .addGap(18, 18, 18)
                        .addComponent(normalRB)
                        .addGap(18, 18, 18)
                        .addComponent(nonPrioRB)
                        .addGap(85, 85, 85)
                        .addComponent(commandeListLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(commandeLabel)
                            .addGap(365, 365, 365)
                            .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(libelleLabel)
                                        .addComponent(typeLabel)
                                        .addComponent(quantiteLabel))
                                    .addGap(44, 44, 44)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(quantiteTB, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                        .addComponent(typeTB)
                                        .addComponent(libelleTB)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(envoyerButton)
                                    .addGap(101, 101, 101)
                                    .addComponent(annulerButton)))
                            .addGap(45, 45, 45)
                            .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(commandeLabel)
                            .addComponent(dateLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urgentRB)
                            .addComponent(normalRB)
                            .addComponent(nonPrioRB)
                            .addComponent(commandeListLabel))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(libelleLabel)
                            .addComponent(libelleTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeLabel)
                            .addComponent(typeTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quantiteLabel)
                            .addComponent(quantiteTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(envoyerButton)
                            .addComponent(annulerButton))))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void urgentRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urgentRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urgentRBActionPerformed

    private void normalRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_normalRBActionPerformed

    private void nonPrioRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonPrioRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nonPrioRBActionPerformed

    private void envoyerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envoyerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_envoyerButtonActionPerformed

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_annulerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(commandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(commandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(commandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(commandForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new commandForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerButton;
    private javax.swing.JList<String> commandList;
    private javax.swing.JScrollPane commandPanel;
    private javax.swing.JLabel commandeLabel;
    private javax.swing.JLabel commandeListLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton envoyerButton;
    private javax.swing.JLabel libelleLabel;
    private javax.swing.JTextField libelleTB;
    private javax.swing.JRadioButton nonPrioRB;
    private javax.swing.JRadioButton normalRB;
    private javax.swing.JLabel quantiteLabel;
    private javax.swing.JTextField quantiteTB;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField typeTB;
    private javax.swing.JRadioButton urgentRB;
    // End of variables declaration//GEN-END:variables
}
