/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackages;

/**
 *
 * @author ante
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UtilisateurLabelLoginForm = new javax.swing.JLabel();
        UtilisateurTextFieldLoginForm = new javax.swing.JTextField();
        MdpLabelLoginForm = new javax.swing.JLabel();
        MdpTextFieldLoginForm = new javax.swing.JTextField();
        MembreRadioLoginForm = new javax.swing.JRadioButton();
        ExterieurRadioLoginForm = new javax.swing.JRadioButton();
        OkButtonLoginForm = new javax.swing.JButton();
        AnnulerButtonLoginForm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Garage HEPL - Authentification d'un utilisateur");
        setName("loginFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        UtilisateurLabelLoginForm.setText("Utilisateur :");
        UtilisateurLabelLoginForm.setName("UtilisateurLabel"); // NOI18N
        getContentPane().add(UtilisateurLabelLoginForm);
        getContentPane().add(UtilisateurTextFieldLoginForm);

        MdpLabelLoginForm.setText("Mot de passe :");
        getContentPane().add(MdpLabelLoginForm);
        getContentPane().add(MdpTextFieldLoginForm);

        MembreRadioLoginForm.setSelected(true);
        MembreRadioLoginForm.setText("Membre du personnel");
        MembreRadioLoginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MembreRadioLoginFormMouseClicked(evt);
            }
        });
        getContentPane().add(MembreRadioLoginForm);

        ExterieurRadioLoginForm.setText("Exterieur habilité");
        ExterieurRadioLoginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExterieurRadioLoginFormMouseClicked(evt);
            }
        });
        getContentPane().add(ExterieurRadioLoginForm);

        OkButtonLoginForm.setText("Ok");
        OkButtonLoginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkButtonLoginFormMouseClicked(evt);
            }
        });
        getContentPane().add(OkButtonLoginForm);

        AnnulerButtonLoginForm.setText("Annuler");
        AnnulerButtonLoginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnnulerButtonLoginFormMouseClicked(evt);
            }
        });
        getContentPane().add(AnnulerButtonLoginForm);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExterieurRadioLoginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExterieurRadioLoginFormMouseClicked
        // TODO add your handling code here:
        MembreRadioLoginForm.setSelected(false);
        ExterieurRadioLoginForm.setSelected(true);
    }//GEN-LAST:event_ExterieurRadioLoginFormMouseClicked

    private void MembreRadioLoginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MembreRadioLoginFormMouseClicked
        // TODO add your handling code here:
        MembreRadioLoginForm.setSelected(true);
        ExterieurRadioLoginForm.setSelected(false);
    }//GEN-LAST:event_MembreRadioLoginFormMouseClicked

    private void AnnulerButtonLoginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnnulerButtonLoginFormMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AnnulerButtonLoginFormMouseClicked

    private void OkButtonLoginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkButtonLoginFormMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OkButtonLoginFormMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerButtonLoginForm;
    private javax.swing.JRadioButton ExterieurRadioLoginForm;
    private javax.swing.JLabel MdpLabelLoginForm;
    private javax.swing.JTextField MdpTextFieldLoginForm;
    private javax.swing.JRadioButton MembreRadioLoginForm;
    private javax.swing.JButton OkButtonLoginForm;
    private javax.swing.JLabel UtilisateurLabelLoginForm;
    private javax.swing.JTextField UtilisateurTextFieldLoginForm;
    // End of variables declaration//GEN-END:variables
}
